name: nepstayapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ##
  # Flutter
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  syncfusion_flutter_pdfviewer: ^20.4.54
  font_awesome_flutter: ^10.0.0
  clipboard: ^0.1.3
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  cherry_toast: ^1.12.0
  google_fonts: ^4.0.4
  mime:
  ##
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  ##
  #  Stage Management
  provider: ^6.1.1
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0

  ##
  # Usefull items
  equatable: ^2.0.5
  dio: ^5.4.0
  dartz: ^0.10.1
  connectivity_plus: ^6.1.2
  get_it: ^8.0.3
  intl: ^0.17.0
  dotted_border: ^2.1.0
  pinput: ^5.0.1
  curved_labeled_navigation_bar: ^2.0.2

  ##
  #  FireBase
  syncfusion_flutter_charts: ^20.4.54
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  # cloud_firestore: ^5.6.3
  # cherry_toast: ^1.11.0
  # firebase_auth: ^5.4.2
  # firebase_dynamic_links: ^6.1.2

  ##
  # Google
  google_maps_flutter: ^2.10.1
  geolocator: ^12.0.0
  google_sign_in: ^6.2.1

  ##
  # Others
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  file_picker: ^8.3.1
  bottom_picker: ^2.4.0
  table_calendar: ^3.0.3
  flutter_staggered_grid_view: ^0.7.0
  charts_flutter: ^0.12.0
  loading_animation_widget: ^1.3.0
  lucide_icons: ^0.257.0
  introduction_screen: ^3.1.17
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Splash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Splash.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/Splash.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/Splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
