// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuz7BvV9f45gSD_HzGs4K_qBWK6mZ8g4',
    appId: '1:242422080119:web:e818902fde7e8fcca65c72',
    messagingSenderId: '242422080119',
    projectId: 'ridenepa-dd565',
    authDomain: 'ridenepa-dd565.firebaseapp.com',
    storageBucket: 'ridenepa-dd565.firebasestorage.app',
    measurementId: 'G-4DC30GE8FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yH72sWqD4_0h0Bkkv_nLeN9sJoYdwaU',
    appId: '1:242422080119:android:a32183861bbf872aa65c72',
    messagingSenderId: '242422080119',
    projectId: 'ridenepa-dd565',
    storageBucket: 'ridenepa-dd565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAL2IA7g1nABzhmTfIkdAJb_ag6ox0zuU',
    appId: '1:242422080119:ios:5774dd72e84e0425a65c72',
    messagingSenderId: '242422080119',
    projectId: 'ridenepa-dd565',
    storageBucket: 'ridenepa-dd565.firebasestorage.app',
    iosBundleId: 'com.ridenepa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAL2IA7g1nABzhmTfIkdAJb_ag6ox0zuU',
    appId: '1:242422080119:ios:9777d288abd51b05a65c72',
    messagingSenderId: '242422080119',
    projectId: 'ridenepa-dd565',
    storageBucket: 'ridenepa-dd565.firebasestorage.app',
    iosBundleId: 'com.example.nepstayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJuz7BvV9f45gSD_HzGs4K_qBWK6mZ8g4',
    appId: '1:242422080119:web:1e6d405f9f4074d1a65c72',
    messagingSenderId: '242422080119',
    projectId: 'ridenepa-dd565',
    authDomain: 'ridenepa-dd565.firebaseapp.com',
    storageBucket: 'ridenepa-dd565.firebasestorage.app',
    measurementId: 'G-9WFGQKQYYX',
  );
}
