// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDd3qTxosEYeHzS1SdBFmTPvQbumCtP5Ow',
//     appId: '1:701616534173:web:ef28cd55f917f081649a74',
//     messagingSenderId: '701616534173',
//     projectId: 'ets-nextstep-57c69',
//     authDomain: 'ets-nextstep-57c69.firebaseapp.com',
//     storageBucket: 'ets-nextstep-57c69.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBVptJXQkaxlTpI6AZqvhd7Uci-7Geh9BQ',
//     appId: '1:701616534173:android:aa5163d7226072f2649a74',
//     messagingSenderId: '701616534173',
//     projectId: 'ets-nextstep-57c69',
//     storageBucket: 'ets-nextstep-57c69.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyARFo6exjd1Ni6_IowR9HGnj9Nks54hWrI',
//     appId: '1:701616534173:ios:ef8bb5b28151bc1c649a74',
//     messagingSenderId: '701616534173',
//     projectId: 'ets-nextstep-57c69',
//     storageBucket: 'ets-nextstep-57c69.appspot.com',
//     iosBundleId: 'com.example.etsApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyARFo6exjd1Ni6_IowR9HGnj9Nks54hWrI',
//     appId: '1:701616534173:ios:ef8bb5b28151bc1c649a74',
//     messagingSenderId: '701616534173',
//     projectId: 'ets-nextstep-57c69',
//     storageBucket: 'ets-nextstep-57c69.appspot.com',
//     iosBundleId: 'com.example.etsApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDd3qTxosEYeHzS1SdBFmTPvQbumCtP5Ow',
//     appId: '1:701616534173:web:0b7730994ef487cd649a74',
//     messagingSenderId: '701616534173',
//     projectId: 'ets-nextstep-57c69',
//     authDomain: 'ets-nextstep-57c69.firebaseapp.com',
//     storageBucket: 'ets-nextstep-57c69.appspot.com',
//   );
// }
